name: Publicar Curiosidad

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar requests
        run: pip install requests deep-translator

      - name: Ejecutar bot
        run: python main.py
